services:
  server:
    build: .
    ports:
      - "3010:3010"
    env_file:
      - ./.env.production
    restart: unless-stopped
  actual:
    image: actualbudget/actual-server:latest
    ports:
      - "5007:5006"
    restart: unless-stopped
    volumes:
      # Change './actual-data' below to the path to the folder you want Actual to store its data in on your server.
      # '/data' is the path Actual will look for its files in by default, so leave that as-is.
      - actual-data:/data

volumes:
  actual-data: